id: I4D2B3B60
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T13:10:49+00:00'
last_modified: '2022-06-08T06:46:39.894279+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W27303
  title: ཀཾ་ཚང་ཡབ་སྲས་དང་དཔལ་སྤུངས་དགོན་པའི་ལོ་རྒྱུས་ངོ་མཚར་དད་པའི་པདྨ་རྒྱས་བྱེད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    '0711':
      image_group_id: I4276
      title: ''
      total_pages: 322
      order: 1
      base_file: 0711.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
