id: P006700
initial_creation_type: ocr
source_metadata:
  id: bdr:W27303
  title: ཀཾ་ཚང་ཡབ་སྲས་དང་དཔལ་སྤུངས་དགོན་པའི་ལོ་རྒྱུས་ངོ་མཚར་དད་པའི་པདྨ་རྒྱས་བྱེད།
  author: ''
  volumes:
    92d03ca1503943c883da7e0bc26011ad:
      image_group_id: I4276
      title: ''
      volume_number: 1
      total_pages: 322
